### PR TITLE
Closes softlayer/sl-ember-test-helpers#156

### PR DESCRIPTION
**Pull request by theoshu**
[Review on Reviewable](https://reviewable.io/reviews/softlayer/sl-ember-test-helpers/158)

### CODE REVIEW

**Comment by notmessenger** [comment]
* The testing story needs to be improved.  Aziz and I spoke and he knows what is desired.
* Have you confirmed the operation of these helpers in an async environment (application acceptance tests)?
** If confirmed add entry to async section of docs
** If not desired, how enforcing not usable in this fashion?
* The importing of sinon in *test-support/helpers/sl/synchronous/global-libraries.js* assumes sinon is installed.  Should this addon force that upon a user during its installation?  Is it only enforced via documentation that it is required?  Is there a way to determine than an import will or did fail so that if we are not installing sinon into an app (if that's the path we take) and a user ignores the docs and uses the helper any way we can give a message as to why?  Perhaps too much work but worth thinking about.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[CHANGELOG.md, line 5 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K3ahmL5EhkeBwe3_mu8:-K3ahmL5EhkeBwe3_mu9:-1474799421) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/97acf3fef0edfa39ed8f3fe32a2f3cc1c8b877c3/CHANGELOG.md#L5)):_
* Neither of the numbers listed correspond to the issue number this PR is against.
* Wrap "globalLibraries" text with back ticks

---

_[README.md, line 104 \[r1\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K3ag9xhnk9wYmneC20B:-K3ag9xhnk9wYmneC20C:-1886962945) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/97acf3fef0edfa39ed8f3fe32a2f3cc1c8b877c3/README.md#L104)):_
Speak to how to use these helpers if how the value of `called` is assigned and need more than that.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-:-K3af7yOpDfssjEpzk_w:173481202)_

**Comment by notmessenger** [comment]
Have you confirmed the operation of these helpers in an async environment (application acceptance tests)?

* If confirmed add entry to async section of docs
* If not desired, how enforcing not usable in this fashion?

---

Reviewed 2 of 2 files at r2, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[CHANGELOG.md, line 5 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d2A1h8ShJOeWd52B1:-K4d2A1h8ShJOeWd52B2:636272088) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/CHANGELOG.md#L5)):*
The number and link should both reflect https://github.com/softlayer/sl-ember-test-helpers/pull/158

---

*[index.js, line 10 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d2Jm3M0b96kxVkItd:-K4d2Jm3M0b96kxVkIte:134705015) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/index.js#L10)):*
* This is needed for the testing environment, not development
* Have you confirmed that this file does not end up being built in the a consuming application's `vendor.js` file?

---

*[test-support/helpers/sl/synchronous/global-libraries.js, line 16 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d2n46vpBEbBf6c3ns:-K4d2n46vpBEbBf6c3nt:571062700) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/test-support/helpers/sl/synchronous/global-libraries.js#L16)):*
https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#block-statements

---

*[test-support/helpers/sl/synchronous/global-libraries.js, line 22 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d2oHwat2QMwtScHDE:-K4d2oHwat2QMwtScHDF:571062700) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/test-support/helpers/sl/synchronous/global-libraries.js#L22)):*
https://github.com/softlayer/ember-style-guide/blob/master/javascript.md#block-statements

---

*[tests/unit/helpers/sl/synchronous/global-libaries-test.js, line 92 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d39vcyO6bEIOncbOE:-K4d39vcyO6bEIOncbOF:1699461445) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/tests/unit/helpers/sl/synchronous/global-libaries-test.js#L92)):*
What about a test that `called()` returns false when nothing is referenced?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-:-K4d3URE_QBV85AcvXHH:-1754424484)*

**Comment by notmessenger** [comment]
Build is failing

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-:-K4d3s24zBhyNOAj1wKA:618820389)*

**Comment by azizpunjani** [comment]
*[tests/unit/helpers/sl/synchronous/global-libaries-test.js, line 92 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d39vcyO6bEIOncbOE:-K50lfE4FpX4SM7TF_gC:705129789) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/tests/unit/helpers/sl/synchronous/global-libaries-test.js#L92)):*
Jeremy, doesn't [this test](https://github.com/softlayer/sl-ember-test-helpers/pull/158/files#diff-5d06fb9d732535e261eded2048e4f539R15) what you are mentioning? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by azizpunjani** [comment]
*[tests/unit/helpers/sl/synchronous/global-libaries-test.js, line 92 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d39vcyO6bEIOncbOE:-K50m5e2X0GC_K8NJIeI:201494498) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/tests/unit/helpers/sl/synchronous/global-libaries-test.js#L92)):*
I guess it's not isolated enough because it triggers events?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by notmessenger** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tests/unit/helpers/sl/synchronous/global-libaries-test.js, line 92 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d39vcyO6bEIOncbOE:-K50vtMIEBLAVyMjQfLG:1840657905) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/tests/unit/helpers/sl/synchronous/global-libaries-test.js#L92)):*
Maybe change the name of the test to align with the references to `called()` like in the other ones asserting the opposite state?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by notmessenger** [comment]
*[index.js, line 10 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d2Jm3M0b96kxVkItd:-K5280oIEZ3BdPOHkld0:-470794784) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/index.js#L10)):*
http://ember-cli.com/user-guide/#test-assets gives some approaches for this scenario

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by azizpunjani** [comment]
@notmessenger this is ready to review when you have a chance.

**Comment by notmessenger** [comment]
* Have you confirmed the operation of these helpers in an async environment (application acceptance tests)?
* If above is confirmed add entry to async section of docs
* If above is not desired, how are we enforcing it is not usable in this fashion?
* What about an uninstall story, that uninstalls the ember-sinon package?  What if that package is being used by something else?
* Nothing in the documentation alerts the user that the ember-simon package will be installed during this add-on's installation.  Should there be?
* There are still outstanding comments from previous revisions that have not been addressed.

---

Reviewed 2 of 2 files at r7.
Review status: 6 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[CHANGELOG.md, line 5 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5fO8vRUQ_n25A7rlNd:-K5fO8vRUQ_n25A7rlNe:1066917470) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/CHANGELOG.md#L5)):*
The number and link should both reflect #156

---

*[index.js, line 10 \[r4\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K4d2Jm3M0b96kxVkItd:-K5fOeCljMtjEHsvh_Eh:-287344361) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/372494cf2971a843fe296a8db7cd58bd5b2d1144/index.js#L10)):*
I now realize that this link was actually guidance for the * ember-cli-build.js* file, which this is not.

---

*[README.md, line 90 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5fOn6UkdLiI-yzKRm4:-K5fOn6UkdLiI-yzKRm5:1029798137) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/README.md#L90)):*
Change "globally scoped" to "globally-scoped"

---

*[README.md, line 107 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5fOvCVBtBaC_hFv2fv:-K5fOvCVBtBaC_hFv2fw:570938928) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/README.md#L107)):*
Change "willInsertElement, didInsertElement, willClearRender and willDestroyElement" to "`willInsertElement`, `didInsertElement`, `willClearRender`, and `willDestroyElement`"

---

*[README.md, line 108 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5fP7vfjCCkiQE-9Xuk:-K5fP7vfjCCkiQE-9Xul:-876744448) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/README.md#L108)):*
"that that"?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-:-K5fPnN5KcZUMSH_thHp:386120850)*

**Comment by notmessenger** [comment]
Reviewed 1 of 2 files at r9.
Review status: 7 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[blueprints/sl-ember-test-helpers/index.js, line 26 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5fSWDWq2S-Pj9_mot9:-K5fSWDWq2S-Pj9_motA:200439247) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/blueprints/sl-ember-test-helpers/index.js#L26)):*
Did you try installing this into an app?  This syntax will not be valid, as it is not transpired.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by notmessenger** [comment]
Review status: 7 of 8 files reviewed at latest revision, 11 unresolved discussions.

---

*[blueprints/sl-ember-test-helpers/index.js, line 33 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5gFC1st9nRw-4sE89b:-K5gFC1st9nRw-4sE89c:46242424) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/blueprints/sl-ember-test-helpers/index.js#L33)):*
Should we use https://github.com/elwayman02/ember-sinon-qunit instead?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by azizpunjani** [comment]
Review status: 4 of 8 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[blueprints/sl-ember-test-helpers/index.js, line 26 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5fSWDWq2S-Pj9_mot9:-K5kcH9HWjx4xr0x-mqc:957554910) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/blueprints/sl-ember-test-helpers/index.js#L26)):*
This will be valid if they are running node version >= 4.0. Arrow functions were introduced in v4.0.0. Should we recommend a node version >=4.0.0? Or do we want to revert the code?

---

*[blueprints/sl-ember-test-helpers/index.js, line 33 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5gFC1st9nRw-4sE89b:-K5kh56sZ0cVUzqhUQVL:-456272161) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/blueprints/sl-ember-test-helpers/index.js#L33)):*
I think for our use case we can do without it. Seems like another layer wrapping `ember-sinon`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by azizpunjani** [comment]
Reviewed 2 of 6 files at r1, 1 of 2 files at r7, 1 of 2 files at r9, 4 of 4 files at r11.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by azizpunjani** [comment]
@notmessenger this is ready for review.

**Comment by notmessenger** [comment]
Merge conflicts

---

Reviewed 4 of 4 files at r11, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[blueprints/sl-ember-test-helpers/index.js, line 26 \[r10\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K5fSWDWq2S-Pj9_mot9:-K7wo_o45jRGMUmDtnqR:2033961210) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/948f7b5756425d279e67ba1815a53c7c71479ed7/blueprints/sl-ember-test-helpers/index.js#L26)):*
I lean toward reversion as if we can easily accommodate all versions with a slight syntax change on our side we don't cause any burden to the user.

---

*[CHANGELOG.md, line 5 \[r13\]](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-K7wowFa8HW7Z4uM9mq3:-K7wowFa8HW7Z4uM9mq4:1066917470) ([raw file](https://github.com/softlayer/sl-ember-test-helpers/blob/9688ba43241db1cda32b39fed49ce05413662887/CHANGELOG.md#L5)):*
The number and link should both reflect #156

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-:-K7woVeJKuZrE9kuH4N_:-385906380)*

**Comment by azizpunjani** [comment]
@notmessenger this is ready for review, made changes you suggested.

**Comment by notmessenger** [comment]
Reviewed 1 of 1 files at r14.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158)*

**Comment by notmessenger** [comment]
There are a few things about this PR that still need to be changed but I am going to merge it and change them myself so we can get this put to bed.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/softlayer/sl-ember-test-helpers/158#-:-K9J-CoT4qr8PKcqDR09:-1159573735)*

**Pull request merged**
